title: Site

columns:
  - width: 1/2
    sections:
      albums: sections/albums
  - width: 1/2
    sections:
      notes: sections/notes
      pages:
        type: pages
        create: default
        template:
          - about
          - home
          - default
          - blog
      commentions:
       type: commentions
       headline: Pending comments